/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package midterm_project;

import java.util.logging.*;
import java.util.*;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.concurrent.*;
import javax.swing.*;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class aggregate_and_parallelprogramming extends javax.swing.JFrame {

    /**
     * Creates new form aggregate_and_parallelprogramming 
     */
    Connection con;
    DefaultTableModel table;
    public aggregate_and_parallelprogramming() {
        initComponents();
        this.setLocationRelativeTo(null);
        createConnection();
        this.table = (DefaultTableModel) tblRecord.getModel();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLocationCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDatePosted = new javax.swing.JTextField();
        cboxAggregate = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecord = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select function:");

        txtLocationCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLocationCodeKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Location Code:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Date Posted:");

        txtDatePosted.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatePostedKeyReleased(evt);
            }
        });

        cboxAggregate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MIN", "MAX", "COUNT", "SUM", "AVG" }));
        cboxAggregate.setAlignmentX(0.0F);
        cboxAggregate.setAlignmentY(0.0F);

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        tblRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LocationCode", "DatePosted", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRecord);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDatePosted, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtLocationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(128, 128, 128)
                                    .addComponent(cboxAggregate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocationCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatePosted, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxAggregate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLocationCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocationCodeKeyReleased
        filterData();
    }//GEN-LAST:event_txtLocationCodeKeyReleased

    private void txtDatePostedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatePostedKeyReleased
        filterData();
    }//GEN-LAST:event_txtDatePostedKeyReleased

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        performAggregate();
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aggregate_and_parallelprogramming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aggregate_and_parallelprogramming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aggregate_and_parallelprogramming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aggregate_and_parallelprogramming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aggregate_and_parallelprogramming().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cboxAggregate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRecord;
    private javax.swing.JTextField txtDatePosted;
    private javax.swing.JTextField txtLocationCode;
    // End of variables declaration//GEN-END:variables
    public void createConnection(){
        String url = "jdbc:mysql://localhost:3306/dbentries";
        String username = "root";
        String password = "YourPassword";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url, username, password);
            System.out.println("Ka connect kana sa db");
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }
//    public void showData(){
//        try {
//            table.setRowCount(0);
//            String query = "SELECT LocationCode, DatePosted, Amount AS TotalAmount FROM tblentry"; // corrected column alias
//            PreparedStatement pst = con.prepareStatement(query);
//            ResultSet rs = pst.executeQuery();
//
//            while(rs.next()){
//                Object[] data = new Object[3];
//                data[0] = rs.getString("LocationCode");
//                data[1] = rs.getDate("DatePosted");
//                data[2] = rs.getDouble("TotalAmount");
//                table.addRow(data);
//            }
//            rs.close();
//            pst.close();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//    }
    public void showData() {
        try {

            String query = "SELECT LocationCode, DatePosted, Amount AS TotalAmount FROM tblentry";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            
            ExecutorService executorService = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors()); 

            while (rs.next()) {
                String locationCode = rs.getString("LocationCode");
                String datePosted = rs.getString("DatePosted");
                double totalAmount = rs.getDouble("TotalAmount");

                
                executorService.submit(() -> {
                    Object[] data = {locationCode, datePosted, totalAmount};
                    table.addRow(data); 
                });
            }

            
            executorService.shutdown();
            executorService.awaitTermination(Long.MAX_VALUE, TimeUnit.NANOSECONDS);

            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void filterData(){
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(table);
    tblRecord.setRowSorter(sorter);

    RowFilter<DefaultTableModel, Object> locationFilter = RowFilter.regexFilter(txtLocationCode.getText(), 0);
    RowFilter<DefaultTableModel, Object> dateFilter = RowFilter.regexFilter(txtDatePosted.getText(), 1);

    RowFilter<DefaultTableModel, Object> compoundRowFilter = RowFilter.andFilter(Arrays.asList(locationFilter, dateFilter));

    sorter.setRowFilter(compoundRowFilter);
    }
    
    public void performAggregate(){
        String aggregateName = (String) cboxAggregate.getSelectedItem();
        
        if(aggregateName.equals("MIN")){
            getMin(txtLocationCode.getText(), txtDatePosted.getText());
        } else if(aggregateName.equals("MAX")){
            getMax(txtLocationCode.getText(), txtDatePosted.getText());
        } else if(aggregateName.equals("COUNT")){
            getCount(txtLocationCode.getText(), txtDatePosted.getText());
        } else if(aggregateName.equals("SUM")){
            getSum(txtLocationCode.getText(), txtDatePosted.getText());
        } else if(aggregateName.equals("AVG")){
            getAvg(txtLocationCode.getText(), txtDatePosted.getText());
        }
    }
    
    public void getMin(String LocationCode, String DatePosted){
        double amount;
        try {
            Statement stmt = con.createStatement();
            ResultSet result = stmt.executeQuery("SELECT MIN(Amount) AS amount FROM dbentries.tblentry WHERE LocationCode = '" + LocationCode +"' AND DatePosted = '" +DatePosted+"'");
            
            if(result.next()){
                 amount = result.getDouble("amount");
                 JOptionPane.showMessageDialog(null, "Minimum: " + amount, "MIN Function", JOptionPane.INFORMATION_MESSAGE);
            }
            
            result.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(aggregate_and_parallelprogramming.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void getMax(String LocationCode, String DatePosted){
        double amount;
        try {
            Statement stmt = con.createStatement();
            ResultSet result = stmt.executeQuery("SELECT MAX(Amount) AS amount FROM dbentries.tblentry WHERE LocationCode = '" + LocationCode +"' AND DatePosted = '" +DatePosted+"'");
            
            if(result.next()){
                 amount = result.getDouble("amount");
                 JOptionPane.showMessageDialog(null, "Maximum: " + amount, "MAX Function", JOptionPane.INFORMATION_MESSAGE);
            }
            result.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(aggregate_and_parallelprogramming.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void getCount(String LocationCode, String DatePosted){
        double amount;
        try {
            Statement stmt = con.createStatement();
            ResultSet result = stmt.executeQuery("SELECT COUNT(Amount) AS amount FROM dbentries.tblentry WHERE LocationCode = '" + LocationCode +"' AND DatePosted = '" +DatePosted+"'");
            
            if(result.next()){
                 amount = result.getDouble("amount");
                 JOptionPane.showMessageDialog(null, "Count: " + amount, "COUNT Function", JOptionPane.INFORMATION_MESSAGE);
            }
            result.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(aggregate_and_parallelprogramming.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void getSum(String LocationCode, String DatePosted){
        double amount;
        try {
            Statement stmt = con.createStatement();
            ResultSet result = stmt.executeQuery("SELECT SUM(Amount) AS amount FROM dbentries.tblentry WHERE LocationCode = '" + LocationCode +"' AND DatePosted = '" +DatePosted+"'");
            
            if(result.next()){
                 amount = result.getDouble("amount");
                 JOptionPane.showMessageDialog(null, "Total amount: " + amount, "SUM Function", JOptionPane.INFORMATION_MESSAGE);
            }
            result.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(aggregate_and_parallelprogramming.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void getAvg(String LocationCode, String DatePosted){
        double amount;
        try {
            Statement stmt = con.createStatement();
            ResultSet result = stmt.executeQuery("SELECT AVG(Amount) AS amount FROM dbentries.tblentry WHERE LocationCode = '" + LocationCode +"' AND DatePosted = '" +DatePosted+"'");
            
            if(result.next()){
                 amount = result.getDouble("amount");
                 JOptionPane.showMessageDialog(null, "Average: " + amount, "AVG Function", JOptionPane.INFORMATION_MESSAGE);
            }
            result.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(aggregate_and_parallelprogramming.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}